- docs/40_development.md
to
- describe current setup(s) - deployed and in development
> Initial description doc for developers

- docs/10_using_dandi.md
- fixing python version (i believe dandi-cli is tested for 3.7+
- updating dandi version
- and example for downloading data wit cli
some questions:
- I can't find a link on the website for downloading a single file or subject
- should I be providing url as `https://identifiers.org/....` or `https://dandiarchive.org/dandiset/<dataset_id>/draft`?
> small updates

- .gitignore
- docs/developer/notes.md
- mkdocs.yml
This PR creates a developer guide section of the handbook and:
- moves the [Developer Notes](https://github.com/dandi/dandiarchive/wiki/Developer-Notes) into it
- moves the "Project structure" section there as well
My overarching goal is to move *all* developer docs into the handbook, leaving only pointers to the handbook (and perhaps quickstart instructions) in the various READMEs.
TODO:
> Create a "developer guide" section

- docs/10_using_dandi.md
Apparently Windows users might not be aware of  "# the rest is a comment"
which could bring confusion and cut-pasting the entire line and thus
trailing -i also into command prompt, but magically omitting the "odd" #.
As a result they would be trying to upload to staging although originally
intending for uploading to the main instance.
Placing such text on a separate line should remove such ambiguity
> ENH: move staging server specification into the text

- docs/30_data_standards.md
Fixed links that were broken for the BIDS Getting Started page and the NWB Conversion Tools user guide per issue [#58 ](https://github.com/dandi/handbook/issues/58).
> Fixed broken links in Data Standards section

- docs/index.md
> Refactor Welcome section

- docs/11_view.md
- docs/12_download.md
- docs/13_upload.md
- docs/14_publish.md
- docs/15_debugging.md
- mkdocs.yml
Fixed items listed in Issue #56 
[ ] - Apply style guidelines to the 5 new subsections added recently to Using Dandi (View, Download, Upload, Publish) and add them to nav TOC under a new umbrella heading "User Guide" (as a parallel to the "Developer Guide" heading).
[ ] -  Make the subheadings parallel with imperative - Download vs Downloading.
[ ] -  In Debugging section, flatten hierarchy by removing Acquiring Debugging Info subsection, only need one heading
> Edit new subsections of Using DANDI

- mkdocs.yml
Having consecutive "About" sections was a little confusing and "About" is an ambiguous section heading; renamed to Terms and Policies to better reflect content.  Fix for issue #60 .
> Rename About section

- mkdocs.yml
Instead of having a separate TOC on the right , it would just
expand already present navigation on the left, IMHO making
1. a better use of screen real estate, 2. no longer requiring
user to jump with mouse from left to right to navigate
> ENH: integrate TOC into the navigation bar

- .codespellrc
- README.md
Closes #96
@bendichter -- I am done as far as I am concerned - please merge or finish it up to your liking.
> DOC: provide rudimentary instructions on how to build website locally

- mkdocs.yml
- The search bar disappeared after #102, because I added a plugin and thus needed to also explicitly add the built-in `search` plugin (see [built-in search plugin docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search-plugin)).
> Add `search` plugin

- docs/50_hub.md
- mkdocs.yml
Add docs for accessing DANDI Hub and for example-notebook best practices
> add docs for DANDI hub

- docs/13_upload.md
- docs/index.md
- mkdocs.yml
> Add MagicLink markdown extension for auto-linking http links

- requirements.txt
- Currently, the [mkdocs-deploy-gh-pages GitHub Action](https://github.com/mhausenblas/mkdocs-deploy-gh-pages) has an older version of `mkdocs-material` installed since it uses an older base image in the [Dockerfile](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/blob/e55ecab6718b449a90ebd4313f1320f9327f1386/Dockerfile#L1) (i.e. version 9.0.6).
- This has caused a recent merge in this repository to fail in deploying.  See [failed run](https://github.com/dandi/handbook/actions/runs/8011989355/job/21886368888#step:4:93).  See [reference in the GitHub Actions run](https://github.com/dandi/handbook/actions/runs/8011989355/job/21886368888#step:4:7) to `mkdocs-material` version 9.0.6 install.  The recent merge is looking for an asset (i.e. X-Twitter logo) that was added in a newer …
> Pin `mkdocs-material` version to force installing a newer version

- docs/14_publish.md
> Clarify steps for publishing a Dandiset

- docs/10_using_dandi.md
- docs/about/policies.md
ATM, if my check is right -- maximal length we can encounter is only 192, so we are quite ok
dandi@drogon:/mnt/backup/dandi/dandisets$ pwd
/mnt/backup/dandi/dandisets
dandi@drogon:/mnt/backup/dandi/dandisets$ declare m=0;for ds in 00*; do git -C $ds ls-tree -r --name-only HEAD; done | awk '{ if (length($0) > max) max = length($0) } END { print max }'
192
When user manages to get over -- server 500s. Filed 
- https://github.com/dandi/dandi-archive/issues/1889
> State explicitly that our current maximal length of the path in dandiset must no exceed 512

- docs/13_upload.md
> Update `Storing Access Credentials` section to improve readability

- docs/13_upload.md
update upload page to point to the NWB GUIDE for conversion and for upload.
Main changes:
* Move conversion to NWB to the top. I found it a bit awkward to have this step in the middle of the upload workflow. If the data is not yet in NWB, the user should probably start there.
* Incorporate NWB GUIDE, both for data conversion and for data upload. The GUIDE now provides a user interface for the entire data upload process, and I think this would be a more comfortable route for most DANDI users.
* Formatting. I like to start each bullet with a title. The text was moved around a bit to try to improve the logical flow
> update upload page 

- mkdocs.yml
> Add site analytics

- docs/100_contribute_docs.md
- docs/index.md
- mkdocs.yml
In order to better describe the `About This Doc` page and inspired by the [Napari docs](https://napari.org/stable/developers/documentation/index.html), I propose:
> Rename the `About This Doc` page to `Contributing Documentation`

- docs/40_development.md
This PR adds some additional structure and content and remixes some existing content (mainly in preparation for adding more information about Mailchimp usage--see #147).
> Update email section

- docs/12_download.md
> Add instructions for the `--preserve-tree` option and add Resource Identifiers URL

- docs/21_models_integration.md
- mkdocs.yml
This PR adds documentation of the definition and usage of DANDI models.
This PR provides a documentation on how DANDI metadata models are integrated across the DANDI ecosystem. The specific changes are:
1. Adding a new section on models integration
2. Updating the navigation to include this new section
3. Enabling support for mermaid diagrams to display the mermaid diagram in this new section
> Add documentation for DANDI models

- requirements.txt
The `mkdocs-material` dependency needs to be upgraded to a newer version to render the mermaid diagram submitted via https://github.com/dandi/dandi-docs/pull/176.
The [GitHub Action](https://github.com/mhausenblas/mkdocs-deploy-gh-pages) that we use to publish the pages uses a docker image that comes with `mkdocs-material` [at version 9.5.17](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/blob/a31c6b13a80e4a4fbb525eeb7a2a78253bb15fa5/Dockerfile#L1C32-L1C38) to build the pages. Since, without the changes in this PR, `mkdocs-material` is constrained to `mkdocs-material>=9.5.10`, `mkdocs-material` at version 9.5.17 would be used to build the pages instead of the newer version needed to render the mermaid diagram correctly. Constraining the `mkdocs-material` dependency to the newer …
> Upgrade the mkdocs-material dependency

- docs/developer-guide/system-architecture.md
The images don't currently resolve:
> Fix image links in the `system-architecture` page

- docs/user-guide-using/accessing-data/downloading.md
Fix typo and add quotes since I am receiving the following error when there is a `=` or `?` symbol in the url.
```bash
% dandi download https://dandiarchive.org/dandiset/000023/0.210914.1900/files?location=sub-541516760
zsh: no matches found: https://dandiarchive.org/dandiset/000023/0.210914.1900/files?location=sub-541516760
```
> Fix download example commands

- docs/user-guide-using/dandi-hub.md
Fixes https://github.com/dandi/dandi-hub/issues/268
Also would be nice if these docs could cover the case for https://github.com/dandi/dandi-hub/issues/262 I think what we would do is have workshop demo leaders file an issue in advance, and we either make them ["env admins"](https://github.com/dandi/dandi-hub/issues/267) of an existing namespace, or create a new namespace for them. 
Heres a WIP skeleton for the docs we'll need for conda-store usage.
> User docs for Conda environments in dandi-hub
