dandi/dandi-docs

docs/10_using_dandi.md
=> Add details on storing the API key

docs/10_using_dandi.md
addressing most comments from #22
=> updating installation instruction; adding comments to the NWB section

docs/10_using_dandi.md
fix https://github.com/dandi/dandiarchive/issues/974
=> talk about dandi staging

docs/10_using_dandi.md
motivated by https://github.com/dandi/helpdesk/discussions/47
=> clarify api keys

README.md
This PR replaces #38 and #37. 
Also addresses Ben's comment to put style sheet in a readme vs. separate file in handbook after collaborating with Roni.
Closes #39.
=> Add a readme that contains the new style sheet

docs/01_introduction.md
Four minor style/grammar edits, however most of the table had already been fixed in a prior commit.
fixes #52
=> Apply minor style and grammar edits

docs/01_introduction.md, mkdocs.yml
=> Increase visibility of Data Standards section

docs/20_project_structure.md, docs/40_development.md
=> Improve dev guide

README.md, docs/10_using_dandi.md, docs/11_view.md, docs/12_download.md, docs/13_upload.md, docs/14_publish.md, docs/20_project_structure.md
=> Remove code format on 'Dandiset'

docs/13_upload.md
We will add --ignore to validate to be used here, but that will be later.
Ref: https://github.com/dandi/dandi-cli/issues/1211  Attn @CodyCBakerPhD
=> Added  a note to ignore  DANDI.NO_DANDISET_FOUND  error for final validation before organize

docs/35_data_licenses.md, mkdocs.yml
This PR is meant to help address https://github.com/dandi/dandi-archive/issues/758. A link to this page will appear in the create dandiset form to help users understand what the license field is about.
=> Add a page on CC licenses

docs/135_validation.md, docs/13_upload.md, mkdocs.yml
Draft PR for Ben to complete to address issue #81
=> Add page for NWB file validation criteria

mkdocs.yml
=> Add social icons to footer

mkdocs.yml
- See [mkdocs-material docs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo) for more information on this feature.
- Fix #86
=> Update homepage link for the logo in the header

docs/13_upload.md, docs/16_account.md, docs/50_hub.md, mkdocs.yml
=> Add a `Create a DANDI Account` page

docs/13_upload.md
Also reformat some surrounding paragraphs so I can actually read them in my editor
=> Document location of encrypted keyfile

mkdocs.yml
Preview: https://kabilar.github.io/handbook/
=> Add `Real-Time Status` link to left menu (i.e. `Upptime`)

docs/16_account.md
I wanted to provide some more details about account policy based on our conversation today
=> add details about intended users

docs/12_download.md
=> Add sections on DataLad and WebDAV access in download chapter

docs/136_metadata.md
=> Fix formatting of list

docs/12_download.md
=> Convert inline code highlighting to code blocks

docs/12_download.md
And expanded on the description underneath
Would partially address https://github.com/dandi/handbook/issues/155 (attn @kabilar ).
=> Make example copy-pasteable by using "draft" instead of "_draft_" placeholder

docs/citing.md, mkdocs.yml
=> Add page on citing dandisets

docs/40_development.md
This PR explains about the presence of Mailchimp and how to update the userbase.
Depends on #146.
=> Add information about Mailchimp usage

docs/CNAME, mkdocs.yml
=> Update site URL

mkdocs.yml
Preview: https://kabilar.github.io/dandi-handbook/
=> Add color scheme for light and dark mode options

docs/about/policies.md, docs/index.md
This PR fixes two broken links in the documents. Each fix is self explanatory and documented in respective commits.
=> Update broken links
